# Generated by Django 5.2.12 on 2026-03-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0002_alter_salesrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
